// <auto-generated />
using System;
using AdvertisingApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvertisingApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303215412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvertisingApp.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Construction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FormatId");

                    b.ToTable("Construction", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.ConstructionFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ConstructionFormat", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PriceType")
                        .HasColumnType("integer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurfaceId");

                    b.ToTable("PriceList", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Surface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionId")
                        .HasColumnType("integer");

                    b.Property<int?>("LoopDuration")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSlots")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotDuration")
                        .HasColumnType("integer");

                    b.Property<int>("SurfaceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId");

                    b.ToTable("Surface", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.SurfaceBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hour")
                        .HasColumnType("integer");

                    b.Property<int>("SlotsOccupied")
                        .HasColumnType("integer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurfaceId");

                    b.ToTable("SurfaceBooking", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.SurfaceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurfaceId");

                    b.ToTable("SurfaceStatus", (string)null);
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Construction", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.District", "District")
                        .WithMany("Constructions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvertisingApp.Core.Entities.ConstructionFormat", "Format")
                        .WithMany("Constructions")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.District", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.PriceList", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.Surface", "Surface")
                        .WithMany("PriceLists")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surface");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Surface", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.Construction", "Construction")
                        .WithMany("Surfaces")
                        .HasForeignKey("ConstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Construction");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.SurfaceBooking", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.Surface", "Surface")
                        .WithMany("Bookings")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surface");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.SurfaceStatus", b =>
                {
                    b.HasOne("AdvertisingApp.Core.Entities.Surface", "Surface")
                        .WithMany("Statuses")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surface");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Construction", b =>
                {
                    b.Navigation("Surfaces");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.ConstructionFormat", b =>
                {
                    b.Navigation("Constructions");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.District", b =>
                {
                    b.Navigation("Constructions");
                });

            modelBuilder.Entity("AdvertisingApp.Core.Entities.Surface", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PriceLists");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
